name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [20.x]  # Puedes probar también con 18.x si tienes problemas

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: List files in src directory  # Añadido para depuración
        run: ls -R src

      - run: npm ci --no-audit
      - name: Build project
        run: npm run build --if-present
        env:
          NODE_ENV: production
      - run: npm test
